name: feature_folder_cli
description: CLI utility to generate folder by feature structure
version: 0.0.1
homepage: https://github.com/RyanDsilva/feature_folder_cli

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.1.1
  logging: ^1.0.1
  path: ^1.8.0

dev_dependencies:
  test: ^1.17.10
