name: feature_folder_cli
description: >-
  CLI utility that generates a folder structure to reduce the repetitive work
  required to setup directories for models, services, repositories, screens and
  widgets.
version: 0.1.1
homepage: https://github.com/RyanDsilva/feature_folder_cli

documentation: https://github.com/RyanDsilva/feature_folder_cli#folder-by-feature-cli-utility

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.1
  mason: ">=0.1.0-dev.26 <0.1.0-dev.27"
  path: ^1.8.2
  recase: ^4.0.0

dev_dependencies:
  test: ^1.21.3

executables:
  ff: main
